
services:
  mqtt-parser:
    build:
      context: ../InfluxDB_parser/
      dockerfile: Dockerfile
    container_name: mqtt-parser
    environment:
      - MQTT_BROKER=172.20.0.2
      - MQTT_PORT=8883
      - MQTT_USER=iot
      - MQTT_PASSWORD=iot-user
      - MQTT_TOPIC=uci/patients/#
      - INFLUXDB_HOST=172.20.0.5
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=iot
      - INFLUXDB_PASSWORD=iot
      - INFLUXDB_DATABASE=mi_base
      - INFLUXDB_SSL=true
      - INFLUXDB_VERIFY_SSL=false
    restart: unless-stopped
    networks:
      mi_red:
        ipv4_address: 172.20.0.8
    depends_on:
      - emqx
      - influxdb1
      - influxdb2
      - nginx_balancer
        
  emqx:
    image: emqx/emqx
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-logs:/opt/emqx/log
      - ./authn.yaml:/opt/emqx/etc/authn.yaml
      - ./certs:/opt/emqx/certs:ro
    environment:
      EMQX_NAME: emqx
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_DASHBOARD__DEFAULT_USERNAME: "iot"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "iot"
      EMQX_AUTH__USER__1__USERNAME: "iot-user"
      EMQX_AUTH__USER__1__PASSWORD: "iot"
      EMQX_LISTENER__SSL__EXTERNAL__ENABLE: "true"
      EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: "/opt/emqx/certs/eqmx.pem"
      EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: "/opt/emqx/certs/eqmx.pem"
    networks:
      mi_red:
        ipv4_address: 172.20.0.2  # IP fija para emqx

  influxdb1:
    image: influxdb:1.8.10
    container_name: influxdb1
    restart: always
    ports:
      - "8087:8086"
    environment:
      - INFLUXDB_DB=mi_base
      - INFLUXDB_ADMIN_USER=iot
      - INFLUXDB_ADMIN_PASSWORD=iot
      - INFLUXDB_USER=iot-user
      - INFLUXDB_PASSWORD=iot
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/influxdb1.crt
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/influxdb1.key
    volumes:
      - influxdb_data1:/var/lib/influxdb
      - ./certs/influxdb1.crt:/etc/ssl/influxdb1.crt:ro
      - ./certs/influxdb1.key:/etc/ssl/influxdb1.key:ro
    networks:
      mi_red:
        ipv4_address: 172.20.0.3  # IP fija para influxdb1

  influxdb2:
    image: influxdb:1.8.10
    container_name: influxdb2
    restart: always
    ports:
      - "8088:8086"
    environment:
      - INFLUXDB_DB=mi_base
      - INFLUXDB_ADMIN_USER=iot
      - INFLUXDB_ADMIN_PASSWORD=iot
      - INFLUXDB_USER=iot-user
      - INFLUXDB_PASSWORD=iot
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/influxdb2.crt
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/influxdb2.key
    volumes:
      - influxdb_data2:/var/lib/influxdb
      - ./certs/influxdb2.crt:/etc/ssl/influxdb2.crt:ro
      - ./certs/influxdb2.key:/etc/ssl/influxdb2.key:ro
    networks:
      mi_red:
        ipv4_address: 172.20.0.4  # IP fija para influxdb2

  nginx_balancer:
    image: nginx:latest
    container_name: nginx_balancer
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./nginx_balancer.conf:/etc/nginx/nginx.conf:ro
      - ./certs/nginx.crt:/etc/nginx/certs/nginx.crt:ro
      - ./certs/nginx.key:/etc/nginx/certs/nginx.key:ro
    depends_on:
      - influxdb1
      - influxdb2
    networks:
      mi_red:
        ipv4_address: 172.20.0.5  # IP fija para nginx_balancer

  nginx_gateway:
    image: nginx:latest
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_gateway.conf:/etc/nginx/nginx.conf:ro
      - ./certs/nginx.crt:/etc/nginx/certs/nginx.crt:ro
      - ./certs/nginx.key:/etc/nginx/certs/nginx.key:ro
    depends_on:
      - emqx
      - grafana
      - influxdb1
      - influxdb2
    networks:
      mi_red:
        ipv4_address: 172.20.0.6  # IP fija para nginx_gateway

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=iot
      - GF_SECURITY_ADMIN_PASSWORD=iot
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_SERVER_SERVER_FORM_SUB_PATH=true
    depends_on:
      - nginx_balancer
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      mi_red:
        ipv4_address: 172.20.0.7  # IP fija para grafana

networks:
  mi_red:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"  # Definir un rango de IP para la red

volumes:
  emqx-data:
  emqx-logs:
  influxdb_data1:
  influxdb_data2:
  grafana_data:

