events {}

http {
    upstream influxdb_primary {
        server influxdb1:8086;
    }

    upstream influxdb_secondary {
        server influxdb2:8086;
    }

    server {
        listen 8086 ssl;
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        location /write {
            proxy_pass https://influxdb_primary;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_connect_timeout 10s;
            proxy_read_timeout 30s;
            proxy_send_timeout 30s;

            post_action @replicate_write;
        }

        location @replicate_write {
            proxy_pass https://influxdb_secondary;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /query {
            proxy_next_upstream error timeout;
            proxy_pass https://influxdb_primary;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            error_page 502 504 = @fallback_query;
        }

        location @fallback_query {
            proxy_pass https://influxdb_secondary;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_next_upstream error timeout;
            proxy_pass https://influxdb_primary;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            error_page 502 504 = @fallback_generic;
        }

        location @fallback_generic {
            proxy_pass https://influxdb_secondary;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

